In [1]:
import pandas as pd

In [ ]:
"""
CREATE A DF, WE WILL SAVE IT AS A CSV SO WE CAN UPLOAD IT TO THE DB

Schedule Table:
staff_id (UUID)
date
time_rangez (List of TimeStamptz) format: [start_time, end_time, start_time, end_time]
is_weekly (bool)
day_of_week (text) format: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
slot_duration (int in minutes)

"""

# Today is 5/7/2024
# Create a schedule for the next month 
# staff_id = 3cf90f46-bd92-445b-aeff-488978ab205d

staff_id = '3cf90f46-bd92-445b-aeff-488978ab205d'
is_weekly = False
today = pd.Timestamp('2024-05-07')
slot_duration = 60


# Create a time range of 9am to 12pm and 1pm to 5pm in New York timezone
# ex: ["2025-05-07 13:00:00+00","2025-05-07 13:00:00+00","2025-05-07 16:00:00+00","2025-05-07 16:00:00+00","2025-05-07 17:00:00+00","2025-05-07 17:00:00+00","2025-05-07 21:00:00+00","2025-05-07 21:00:00+00"]
# LETS REWRITE TO USE EASTERN TIME ZONE
# rewritten ex: ["2025-05-07 13:00:00-04","2025-05-07 13:00:00-04","2025-05-07 16:00:00-04","2025-05-07 16:00:00-04","2025-05-07 17:00:00-04","2025-05-07 17:00:00-04","2025-05-07 21:00:00-04","2025-05-07 21:00:00-04"]

time_range = ["2025-05-07 13:00:00-04","2025-05-07 13:00:00-04","2025-05-07 16:00:00-04","2025-05-07 16:00:00-04","2025-05-07 17:00:00-04","2025-05-07 17:00:00-04","2025-05-07 21:00:00-04","2025-05-07 21:00:00-04"]

# Create a schedule entry for Mon - Fri for the next month
schedule = []
for i in range(30):
    date = today + pd.Timedelta(days=i)
    if date.dayofweek < 5:  # Monday to Friday
        schedule.append({
            'staff_id': staff_id,
            'date': date,
            'time_rangez': time_range,
            'is_weekly': is_weekly,
            'day_of_week': date.day_name(),
            'slot_duration': slot_duration
        })

# Create a DataFrame from the schedule
df = pd.DataFrame(schedule)
df.head(20)

,staff_id,date,time_rangez,is_weekly,day_of_week,slot_duration
0,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-07,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Tuesday,60
1,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-08,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Wednesday,60
2,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-09,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Thursday,60
3,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-10,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Friday,60
4,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-13,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Monday,60
5,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-14,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Tuesday,60
6,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-15,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Wednesday,60
7,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-16,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Thursday,60
8,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-17,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Friday,60
9,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-20,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Monday,60
10,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-21,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Tuesday,60
11,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-22,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Wednesday,60
12,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-23,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Thursday,60
13,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-24,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Friday,60
14,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-27,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Monday,60
15,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-28,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Tuesday,60
16,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-29,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Wednesday,60
17,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-30,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Thursday,60
18,3cf90f46-bd92-445b-aeff-488978ab205d,2024-05-31,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Friday,60
19,3cf90f46-bd92-445b-aeff-488978ab205d,2024-06-03,"[2024-05-07T13:00:00+00:00, 2024-05-07T16:00:0...",False,Monday,60

In [22]:
# Print time range
print(time_range   )

['2024-05-07T13:00:00+00:00', '2024-05-07T16:00:00+00:00', '2024-05-07T17:00:00+00:00', '2024-05-07T21:00:00+00:00']

In [23]:
# Save the DataFrame to a CSV file
df.to_csv('schedule1.csv', index=False)

In [6]:
# For each schedule entry, we will have to create time slots
"""
time slots table:
time_slot_id 
schedule_id (UUID)
start_time (timestamptz)
end_time (timestamptz)
status (text) format: ['available', 'booked', 'unavailable']


Each schedule entry will have a time slots based on the time ranges and the slot duration
Ex:
time range: [[2024-05-07 09:00:00, 2024-05-07 12:00:00], [2024-05-07 13:00:00, 2024-05-07 17:00:00]]
slot duration: 60

time slots: 
2024-05-07 09:00:00, 2024-05-07 10:00:00
2024-05-07 10:00:00, 2024-05-07 11:00:00
2024-05-07 11:00:00, 2024-05-07 12:00:00
2024-05-07 13:00:00, 2024-05-07 14:00:00
2024-05-07 14:00:00, 2024-05-07 15:00:00 ...
"""
# Create a time slots table
time_slots = []
for index, row in df.iterrows():
    for time_range in row['time_rangez']:
        start_time = time_range[0]
        end_time = time_range[1]
        while start_time < end_time:
            time_slots.append({
                'schedule_id': index,
                'start_time': start_time,
                'end_time': start_time + pd.Timedelta(minutes=slot_duration),
                'status': 'available'
            })
            start_time += pd.Timedelta(minutes=slot_duration)
# Create a DataFrame from the time slots
time_slots_df = pd.DataFrame(time_slots)
time_slots_df.head(20)

    schedule_id          start_time            end_time     status
0             0 2024-05-07 09:00:00 2024-05-07 10:00:00  available
1             0 2024-05-07 10:00:00 2024-05-07 11:00:00  available
2             0 2024-05-07 11:00:00 2024-05-07 12:00:00  available
3             0 2024-05-07 13:00:00 2024-05-07 14:00:00  available
4             0 2024-05-07 14:00:00 2024-05-07 15:00:00  available
5             0 2024-05-07 15:00:00 2024-05-07 16:00:00  available
6             0 2024-05-07 16:00:00 2024-05-07 17:00:00  available
7             1 2024-05-07 09:00:00 2024-05-07 10:00:00  available
8             1 2024-05-07 10:00:00 2024-05-07 11:00:00  available
9             1 2024-05-07 11:00:00 2024-05-07 12:00:00  available
10            1 2024-05-07 13:00:00 2024-05-07 14:00:00  available
11            1 2024-05-07 14:00:00 2024-05-07 15:00:00  available
12            1 2024-05-07 15:00:00 2024-05-07 16:00:00  available
13            1 2024-05-07 16:00:00 2024-05-07 17:00:00  available
14            2 2024-05-07 09:00:00 2024-05-07 10:00:00  available
15            2 2024-05-07 10:00:00 2024-05-07 11:00:00  available
16            2 2024-05-07 11:00:00 2024-05-07 12:00:00  available
17            2 2024-05-07 13:00:00 2024-05-07 14:00:00  available
18            2 2024-05-07 14:00:00 2024-05-07 15:00:00  available
19            2 2024-05-07 15:00:00 2024-05-07 16:00:00  available